---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  firefox: "56.0"

cache:
  yarn: true

env:
  - EMBER_TRY_SCENARIO=ember-2.16.X
  - EMBER_TRY_SCENARIO=ember-2.18.X
  - EMBER_TRY_SCENARIO=ember-beta

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - yarn install --no-lockfile --non-interactive

script:
  - npm run lint:js
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
